export type Currency = 'USD' | 'EUR' | 'TRY' | 'GBP';
export type PermissionType = 'VIEW_DASHBOARD' | 'MANAGE_COMPANIES' | 'MANAGE_PROJECTS' | 'MANAGE_TRANSACTIONS' | 'MANAGE_ROLES' | 'VIEW_REPORTS' | 'MANAGE_ENTITIES' | 'MANAGE_DOCUMENTS' | 'MANAGE_BANK_ACCOUNTS' | 'MANAGE_INVOICES' | 'MANAGE_TAXES';
export type EntityType = 'customer' | 'supplier' | 'subcontractor' | 'employee' | 'other';
export type ProjectStatus = 'active' | 'completed' | 'hold' | 'cancelled';
export type ProjectPriority = 'low' | 'medium' | 'high';

export interface Role {
  id: string;
  name: string;
  description: string;
  permissions: PermissionType[];
}

export interface Document {
  id: string;
  name: string;
  type: 'pdf' | 'image' | 'spreadsheet' | 'word' | 'other';
  size: string;
  uploadDate: string;
  uploaderId: string;
  category: 'contract' | 'invoice' | 'project' | 'personnel' | 'general';
  relatedId?: string; // Proje, Sözleşme veya Personel ID'si
  url: string;
}

export interface User {
  id: string;
  name: string;
  email: string; // Added
  title?: string; // Added
  password?: string; // Added
  roleId: string;
  avatar: string;
}

export interface Company {
  id: string;
  name: string;
  taxNumber: string;
  baseCurrency: Currency;
  address: string;
  phone: string;
  email: string;
  website: string;
  logoColor: string;
}

export interface Entity {
  id: string;
  name: string;
  type: EntityType;
  taxOffice?: string;
  taxNumber?: string;
  email?: string;
  phone?: string;
  address?: string;
  iban?: string;
  bankName?: string;
  status: 'active' | 'passive';
}

export interface Project {
  id: string;
  code: string;
  companyId: string;
  customerId?: string; // Projenin yapıldığı müşteri (Cari Hesap)
  name: string;
  description?: string;
  managerId?: string;
  agreementCurrency: Currency;
  budget: number;
  startDate: string;
  endDate?: string;
  status: ProjectStatus;
  priority: ProjectPriority;
  location?: string;
  tags: string[];
  progress?: number;
}

export interface Transaction {
  id: string;
  projectId: string;
  type: 'income' | 'expense';
  amount: number; // KDV hariç tutar
  currency: Currency;
  exchangeRate: number;
  date: string;
  description: string;
  category: string;
  invoiceNumber?: string; // Fatura Numarası
  contractId?: string; // Bağlı Sözleşme ID
  taxes?: TaxItem[]; // Dinamik vergi kalemleri
  totalAmount?: number; // Vergi dahil toplam tutar
  documentUrl?: string; // Fatura/Dekont Dosyası (PDF/Image)
  isVatIncluded?: boolean; // KDV dahil mi? (false = KDV hariç, true = KDV dahil)
  isAutoGenerated?: boolean; // Ödemeden otomatik oluşturuldu mu?
  bankAccountId?: string; // Banka Hesap ID
  bankCardId?: string; // Banka Kart ID
  invoiceId?: string; // Fatura ID
  bankAccount?: BankAccount; // İlişkili banka hesabı
  bankCard?: BankCard; // İlişkili banka kartı
  invoice?: Invoice; // İlişkili fatura
}

export interface Tax {
  id: string;
  name: string;
  code?: string;
  rate: number;
  calculationType: 'percentage' | 'fixed'; // Yüzde mi, sabit tutar mı?
  baseType: 'amount' | 'vat' | 'total'; // Hesaplama tabanı: tutar, KDV, toplam
  description?: string;
  isActive: boolean;
  order: number;
}

export interface TaxItem {
  id: string;
  taxId: string; // Tax ID'si
  name: string;
  rate: number;
  amount: number;
  calculationType: 'percentage' | 'fixed';
  baseType: 'amount' | 'vat' | 'total';
}

export type ContractStatus = 'draft' | 'active' | 'completed' | 'cancelled' | 'expired';
export type ContractType = 'customer_agreement' | 'subcontractor_agreement' | 'purchase_order' | 'service_agreement';

export interface Contract {
  id: string;
  code: string; // CNT-2024-001
  name: string;
  type: ContractType;
  status: ContractStatus;
  projectId: string;
  companyId: string;
  entityId: string; // Sözleşmenin yapıldığı taraf (Cari)
  startDate: string;
  endDate: string;
  amount: number; // Sözleşme Bedeli (KDV hariç)
  currency: Currency;
  paymentTerms?: string; // Ödeme Koşulları (Metin)
  description?: string;
  attachments: string[]; // Dosya URL'leri
  isVatIncluded?: boolean; // KDV dahil mi? (false = KDV hariç, true = KDV dahil)
}

export type BankAccountType = 'checking' | 'savings' | 'deposit' | 'foreign';
export type BankCardType = 'credit' | 'debit' | 'prepaid';

export interface BankBranch {
  id: string;
  name: string;
  code?: string;
  address?: string;
  phone?: string;
  email?: string;
  city?: string;
  district?: string;
  companyId: string;
  isActive: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface BankAccount {
  id: string;
  accountName: string;
  accountNumber: string;
  iban?: string;
  currency: Currency;
  accountType: BankAccountType;
  bankName: string;
  branchId?: string;
  companyId: string;
  balance: number;
  isActive: boolean;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  branch?: BankBranch;
}

export interface BankCard {
  id: string;
  cardName: string;
  cardNumber?: string; // Son 4 hanesi
  cardType: BankCardType;
  bankName: string;
  accountId?: string;
  companyId: string;
  expiryDate?: string;
  limit?: number;
  isActive: boolean;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  account?: BankAccount;
}

export type InvoiceType = 'incoming' | 'outgoing';
export type InvoiceStatus = 'draft' | 'issued' | 'paid' | 'cancelled' | 'overdue';
export type PaymentMethod = 'cash' | 'transfer' | 'card' | 'check';
export type PaymentStatus = 'pending' | 'completed' | 'failed' | 'cancelled';
export type PaymentType = 'incoming' | 'outgoing'; // incoming = gelen ödeme (bize ödeniyor), outgoing = giden ödeme (biz ödüyoruz)

export interface Invoice {
  id: string;
  invoiceNumber: string;
  invoiceType: InvoiceType;
  invoiceDate: string;
  dueDate?: string;
  amount: number; // KDV hariç tutar
  vatAmount: number; // KDV tutarı
  totalAmount: number; // Toplam tutar
  currency: Currency;
  status: InvoiceStatus;
  projectId?: string;
  companyId: string;
  entityId: string;
  contractId?: string;
  description?: string;
  documentUrl?: string;
  isVatIncluded: boolean;
  taxes?: TaxItem[];
  notes?: string;
  createdAt?: string;
  updatedAt?: string;
  project?: Project;
  company?: Company;
  entity?: Entity;
  contract?: Contract;
  payments?: Payment[];
}

export interface Payment {
  id: string;
  paymentType: PaymentType; // incoming = gelen ödeme, outgoing = giden ödeme
  paymentDate: string;
  amount: number;
  currency: Currency;
  exchangeRate: number; // Döviz kuru
  paymentMethod: PaymentMethod;
  invoiceId?: string;
  bankAccountId?: string;
  bankCardId?: string;
  transactionId?: string; // Otomatik oluşturulan Transaction
  description?: string;
  referenceNumber?: string;
  status: PaymentStatus;
  documentUrl?: string;
  createdAt?: string;
  updatedAt?: string;
  invoice?: Invoice;
  bankAccount?: BankAccount;
  bankCard?: BankCard;
}

